### ISSUE TITLE
Determine how to handle NSB.Raw

### ISSUE THREAD

**Issue by kbaley** [Particular/ServiceControl.TransportAdapter#3]
The ServiceControl.TransportAdapter project has a dependency on https://github.com/SzymonPobiega/NServiceBus.Raw, a community project by @SzymonPobiega. Need to determine if this is okay to leave as is and if not, how to mitigate it.

Related issue: https://github.com/Particular/NServiceBus/pull/5068

Options:
- Leave as is
- Adopt NSB.Raw as a supported package
- Copy the NSB.Raw code into this project
- Remove NSB.Raw completely and use NSB core (not sure this is possible)

**Comment by SzymonPobiega** [comment]
As we discussed on Slack, we can leave that one open here as it does not stop us from adopting the actual adapter code.

**Comment by kbaley** [comment]
Issue has moved to https://github.com/Particular/PlatformDevelopment/issues/1526
