### ISSUE TITLE
Message Id format requirements may vary between transports

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceControl.TransportAdapter#34]
For instance, if you have endpoints running on MSMQ and you route messages through a TransportAdapter to ServiceControl running on SQL, those messages can not be retried.

When ServiceControl tries to send the messages to it's staging queue, the SQL transport tries to interpret the Message Id as a Guid. Message Ids in MSMQ are not Guids, they have a suffix on them.

**Comment by mikeminutillo** [comment]
The TransportAdapter cannot simply replace MessageId as it is referred to in other features and headers for other messages (Related To and Saga Changes).

**Comment by mikeminutillo** [comment]
Proposal:

- When TransportAdapter forwards a message from Endpoint to ServiceControl
  - Read the Message Id of the incoming message and attach it as a header `Adapter-OriginalMessageId` to the outgoing message
  - Do not copy the Message Id from the incoming message to the outgoing message. Allow the outgoing transport to use it's own algorithm to assign a message id.
- When ServiceControl ingests a message
  - If the `Adapter-OriginalMessageId` header is present then:
    - Overwrite the Message Id written to the database with this value
    - Add metadata for `Adapter-RetryMessageId` containing the original incoming message id
    - Need to ensure that all places in the SC code that rely on Message Id are getting the corrected value
- When ServiceControl retries a message
  - If the `Adapter-RetryMessageId` metadata is present then:
    - Overwrite the outgoing message id with this value
- When the TransportAdapter is forwarding a message from ServiceControl to the endpoints
  - If the `Adapter-OriginalMessageId` header is present then:
    - Overwrite the outgoing message id with this value
    - Do not copy this header to the outgoing message

**Comment by SzymonPobiega** [comment]
That sounds good.

**Comment by ramonsmits** [comment]
The message ID can be any type of string, you mean the transport message ID? During a retry the transport message ID in most cases should not be set to the message ID. The message ID should only be retrieved from the headers, unless not present, then it could use the transport message ID

**Comment by mikeminutillo** [comment]
@ramonsmits ServiceControl is running on top of NSB CoreV5. When it dispatches a Transport Message, the SQL Transport tries to convert the transportMessage.Id property into a Guid. In Core V5 the transportMessage.Id property simply accesses the NServiceBus.MessageId header. That header was created by the MSMQ Transport. 

We don't see this problem happening in the Transport Adapter because it is running on the Core V6 of the transport. The Core V6 version of the transport does not try to parse the Id as a Guid. It always generates it's own transport identifier and leaves the logical NServiceBus identifier in the headers alone. 

So, MSMQ generates a message id and sets it as the outgoing message header (NServiceBus.MessageId). The message gets handled and audited. The Transport Adapter picks it up and generates a new transport message id for the message. ServiceControl ingests this message and records the (NServiceBus.MessageId) header. When the user attempts to retry the message, we retrieve the message with the headers from the database and hand it off to the SQL transport for dispatch. The SQL Transport complains that the transport id is not a guid.

**Comment by mikeminutillo** [comment]
I have set this up in my own environment and it works fine. NServiceBus endpoints (running v5 or v6) can send audit a message via a transport adapter to ServiceControl running on SQL Transport. And those messages are able to be retried just fine.
